### ISSUE TITLE
SCLK pin should be an inout with clock stretching?

### ISSUE THREAD

**Issue by lucask07** [opalkelly-opensource/I2CController#1]
I was working with a part that supports clock stretching. I2C read back was inconsistent with SCL configured as an output:
`output wire        gyro_scl`
at the top level module. 

This is inconsistent with the inputs/outputs of the `I2CController.v` and `I2CTokenizer.v` code. In both these modules, SCLK is an `inout`

After modifying the top-level example to read:
`inout wire        gyro_scl`

I2C read back was consistent.

**Comment by emusan** [comment]
Thanks for pointing that out, we've resolved this now with commit c9a8bab.
