### ISSUE TITLE
Cpp host code doesn't wait for trigger

### ISSUE THREAD

**Issue by lucask07** [opalkelly-opensource/I2CController#2]
Line 184 and 227 in Software/Cxx/i2c_api.cpp read:

`	
if (0 == m_dev->IsTriggered(I2C_TRIGOUT, (1<<I2C_TRIGOUT_DONE))) {
`
The 0== should not be included if the intent is to wait for the I2C to be done before proceeding. In my tests, I periodically received wrong values from the I2C interface (which were not seen on an oscilloscope). This was fixed by changing the API code to wait for a trigger.

**Comment by emusan** [comment]
This has been resolved in f24c2d62783ecc3307c6275c6e177daef66a121c. Thanks again for pointing it out!
